#!/bin/bash

# Executed against the 'headless-round-trip' scenario in
# test/protondrive/scenarios.json: the protondrive feature in a clean
# container with no desktop keyring, plus restic as a fixture.
#
# Live round trip (CIT-378):
#   1. sign in with PROTON_DRIVE_CREDENTIALS_STORE=pass, completing the
#      printed URL on another device;
#   2. back up the investigation's baseline and the agent's run as two
#      restic snapshots and upload the repository with `filesystem upload`;
#   3. from a fresh process, list it back with `filesystem list --json`;
#   4. download it with `filesystem download` and read it with restic
#      (`snapshots`, `diff`, `dump`) from a fresh process.
#
# Sign-in needs a person to open the URL, so the live half only runs when
# PROTON_DRIVE_LIVE=1 is set on the host:
#
#    PROTON_DRIVE_LIVE=1 devcontainer features test -f protondrive \
#        --skip-autogenerated --skip-duplicated .
#
# Without it (CI), the install checks still run and the outcome is
# recorded as "skipped".

set -e

source dev-container-features-test-lib

# SCRIPT_FOLDER is bind-mounted from the host, so evidence written here
# outlives the container (see test/pass-cli/restic-backup.sh).
EVIDENCE_DIR="$SCRIPT_FOLDER/evidence"
mkdir -p "$EVIDENCE_DIR"

SCENARIO_OUTCOME=""
RUN_ID="protondrive-scenario-$(date -u +%Y%m%dT%H%M%SZ)-$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
REMOTE_RUN="/my-files/$RUN_ID"
SIGNED_IN=""
UPLOADED=""

on_exit() {
    local exit_code=$?
    if [ -n "$UPLOADED" ]; then
        proton-drive filesystem trash "$REMOTE_RUN" || true
    fi
    if [ -n "$SIGNED_IN" ]; then
        proton-drive auth logout || true
    fi
    if [ -z "$SCENARIO_OUTCOME" ]; then
        if [ "$exit_code" -eq 0 ]; then
            SCENARIO_OUTCOME="passed"
        else
            SCENARIO_OUTCOME="failed"
        fi
    fi
    printf '{"outcome": "%s"}\n' "$SCENARIO_OUTCOME" > "$EVIDENCE_DIR/scenario-outcome.json" || true
}
trap on_exit EXIT

# Recorded on every run, live or not.
proton-drive version | tee "$EVIDENCE_DIR/proton-drive-version.txt"
check "proton-drive is the pinned release" grep -F 0.9.0 "$EVIDENCE_DIR/proton-drive-version.txt"
check "session store is pass" bash -c '[ "$PROTON_DRIVE_CREDENTIALS_STORE" = pass ]'
check "no desktop keyring is installed" bash -c \
    '! command -v gnome-keyring-daemon && ! command -v kwalletd5 && ! command -v kwalletd6 && ! ldconfig -p | grep -q libsecret'

if [ "${PROTON_DRIVE_LIVE:-}" != "1" ]; then
    echo -e "\nSkipping the live round trip: PROTON_DRIVE_LIVE=1 not set.\n"
    SCENARIO_OUTCOME="skipped"
    reportResults
    exit 0
fi

# 1. Session store: a fresh GPG key without a passphrase (no pinentry in a
#    headless container) and a pass store keyed to it. Created now, not at
#    image build.
gpg --batch --passphrase '' --quick-gen-key "protondrive scenario <$RUN_ID@localhost>" default default never
GPG_FPR="$(gpg --list-keys --with-colons "$RUN_ID@localhost" | awk -F: '/^fpr:/ { print $10; exit }')"
pass init "$GPG_FPR"

echo -e "\nOpen the sign-in URL below on another device. Waiting up to 15 minutes...\n"
timeout 900 proton-drive auth login
SIGNED_IN=1
check "the session is stored in pass" \
    bash -c "pass show ch.proton.drive/drive-sdk-cli/auth-session >/dev/null"

# 2. One restic snapshot in a local repository, uploaded as a folder.
# $LOCAL_RUN holds only the repository, so uploading it to /my-files
# creates $REMOTE_RUN/restic-repo.
LOCAL_RUN="$(mktemp -d)/$RUN_ID"
mkdir -p "$LOCAL_RUN"
export RESTIC_REPOSITORY="$LOCAL_RUN/restic-repo"
RESTIC_PASSWORD="$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
export RESTIC_PASSWORD
restic init

# Two snapshots of the investigation's own files (CIT-389), taken from the
# ArchiveInDrive story's fixture (test/protondrive/investigation/README.md):
# the baseline, then the agent's run with the story's changes. Both back up
# the relative path `inputs` from the same folder, so the snapshot trees hold
# /inputs/... and `restic diff` compares like with like.
QUESTION="Does release-2026-10 still keep the private file private?"
WORK="$(mktemp -d)/release-2026-10"
mkdir -p "$WORK"
cp -r "$SCRIPT_FOLDER/investigation/baseline/inputs" "$WORK/"
(cd "$WORK" && restic backup --host investigations --tag baseline inputs)
rm -rf "$WORK/inputs"
cp -r "$SCRIPT_FOLDER/investigation/agent/inputs" "$WORK/"
(cd "$WORK" && restic backup --host investigations --tag "$QUESTION" inputs)
BASELINE_ID="$(restic snapshots --json --tag baseline | jq -r '.[0].id')"
SNAPSHOT_ID="$(restic snapshots --json --tag "$QUESTION" | jq -r '.[0].id')"
printf 'baseline %s\nagent %s\n' "$BASELINE_ID" "$SNAPSHOT_ID" > "$EVIDENCE_DIR/snapshot-id.txt"
check "restic produced the baseline and the agent's snapshot" \
    bash -c "[ -f \"$RESTIC_REPOSITORY/snapshots/$BASELINE_ID\" ] && [ -f \"$RESTIC_REPOSITORY/snapshots/$SNAPSHOT_ID\" ]"

# Strategies are set so a conflict never prompts and hangs the run.
UPLOADED=1
proton-drive filesystem upload -d merge -f skip -t "$LOCAL_RUN" /my-files

# 3. A fresh process reloads the session from pass and lists each folder
#    level: run folder -> repository -> snapshots.
proton-drive filesystem list --json "$REMOTE_RUN" > "$EVIDENCE_DIR/list-run.json"
proton-drive filesystem list --json "$REMOTE_RUN/restic-repo" > "$EVIDENCE_DIR/list-restic-repo.json"
proton-drive filesystem list --json "$REMOTE_RUN/restic-repo/snapshots" > "$EVIDENCE_DIR/list.json"
check "both snapshots are listed back from Drive" \
    bash -c "jq -e --arg b \"$BASELINE_ID\" --arg a \"$SNAPSHOT_ID\" 'map(.name.value // .name) | (index(\$b) != null and index(\$a) != null)' \"$EVIDENCE_DIR/list.json\""

# 4. Download the repository back into an empty folder and open it with
#    restic from a fresh process. Restic files never change once written,
#    so skipping an existing local file is always right, and the strategies
#    mean a conflict never prompts.
DOWNLOAD_DIR="$(mktemp -d)"
proton-drive filesystem download -d merge -f skip "$REMOTE_RUN/restic-repo" "$DOWNLOAD_DIR"
REPO_COPY="$(dirname "$(dirname "$(find "$DOWNLOAD_DIR" -path "*/snapshots/$SNAPSHOT_ID" | head -1)")")"
( cd "$DOWNLOAD_DIR" && find . -type f | sort ) > "$EVIDENCE_DIR/download-tree.txt"
check "the downloaded repository has both snapshot files" \
    bash -c "[ -f \"$REPO_COPY/snapshots/$BASELINE_ID\" ] && [ -f \"$REPO_COPY/snapshots/$SNAPSHOT_ID\" ]"

fresh_restic() {
    env -i PATH="$PATH" HOME="$HOME" RESTIC_PASSWORD="$RESTIC_PASSWORD" restic -r "$REPO_COPY" "$@"
}
fresh_restic snapshots --json > "$EVIDENCE_DIR/restic-snapshots.json"
fresh_restic diff --json "$BASELINE_ID" "$SNAPSHOT_ID" > "$EVIDENCE_DIR/restic-diff.ndjson"
mkdir -p "$EVIDENCE_DIR/dump"
for changed in inputs/observations/forged-read.json inputs/canary-reads.txt inputs/run_arms.sh; do
    mkdir -p "$EVIDENCE_DIR/dump/$(dirname "$changed")"
    fresh_restic dump "$SNAPSHOT_ID" "/$changed" > "$EVIDENCE_DIR/dump/$changed"
done

check "restic opens both downloaded snapshots" \
    bash -c "jq -e --arg b \"$BASELINE_ID\" --arg a \"$SNAPSHOT_ID\" 'map(.id) | (index(\$b) != null and index(\$a) != null)' \"$EVIDENCE_DIR/restic-snapshots.json\""
check "restic diff shows forged-read.json added and both inputs modified" \
    bash -c "jq -rs '[.[] | select(.message_type == \"change\") | .modifier + \" \" + .path] | sort | join(\",\")' \"$EVIDENCE_DIR/restic-diff.ndjson\" | grep -Fx '+ /inputs/observations/,+ /inputs/observations/forged-read.json,M /inputs/canary-reads.txt,M /inputs/run_arms.sh'"
check "restic dump returns the agent's files byte for byte" \
    diff -r "$SCRIPT_FOLDER/investigation/agent/inputs" "$EVIDENCE_DIR/dump/inputs"

reportResults
