/* This file was generated by `pkl-typescript` from Pkl module `evidence`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// CIT-147 package contract: the versioned, externally-consumable shape of
// one exported feature-test run + its restic snapshot evidence.
//
// Two roles live in this repo for Pkl (see capability-spike/README.md for
// the domain-facts role): this module is the *package contract* --
// `internal/export` renders a concrete `EvidencePackage` instance as Pkl
// source and evaluates it against this schema (real pkl-go evaluation, not
// just Go-side struct construction) so a structurally invalid export fails
// loudly during CI/export rather than being silently packaged.
//
// `CapabilityFact`/`CapabilityGrant`/`CapabilityObservation`/
// `ReconciliationFlag` mirror capability-spike's Go types field-for-field
// (diagnostic.Diagnostic, supervisor.Grant, runtime.Observation,
// reconcile.Flag) so CIT-146's devcontainer scenario becomes an additional
// input later without renaming anything here.
export interface Evidence {
}

// Ref: Pkl class `evidence.ExecutionIdentity`.
// Binds one export to its repository revision, GitHub Actions run/attempt,
// and job/step references -- sourced from the Actions Jobs API
// (`internal/ghactions`), not scraped from this workflow's own log output.
export interface ExecutionIdentity {
  sourceRevision: string

  workflowRunId: string

  workflowRunAttempt: string

  runUrl: string

  jobName: string

  stepRefs: Array<string>

  // The single name used consistently across the feature test, the pass-cli
  // `tag` assignment, the restic snapshot tag, and (eventually) TK lesson
  // identity.
  scenarioName: string

  // The exact restic snapshot ID `color` produced *during this run*,
  // distinguished (via a before/after set difference in restic-backup.sh)
  // from any other snapshot that happens to share the scenario's tag from a
  // previous run. `null` when this run produced no snapshot (e.g. the
  // scenario was skipped or failed before backing up).
  snapshotId: string|null
}

// Ref: Pkl class `evidence.CheckResult`.
// One check/fact's recorded outcome. `detail` carries the structured
// diagnostic/failure text when available (e.g. a JUnit `<failure message>`
// for a Pkl-test-backed fact) -- never a scraped log line.
export interface CheckResult {
  label: string

  outcome: Outcome

  detail: string|null
}

// Ref: Pkl class `evidence.ScenarioResult`.
// A scenario with no deeper structured test runner beneath it (e.g. a plain
// bash `check`/`reportResults` scenario like `restic-backup`) legitimately
// has an empty `checks` listing -- its `outcome` still reflects the real
// GitHub Actions job/step conclusion, just without per-check granularity.
export interface ScenarioResult {
  scenarioName: string

  outcome: Outcome

  checks: Array<CheckResult>
}

// Ref: Pkl class `evidence.SnapshotRef`.
export interface SnapshotRef {
  id: string

  shortId: string

  tag: string

  takenAt: string
}

// Ref: Pkl class `evidence.FileTreeEntry`.
export interface FileTreeEntry {
  path: string

  type: "file" | "dir"

  size: number|null

  // The restic snapshot this entry was listed from (`restic ls`'s own
  // "snapshot" header line carries this) -- required so a future package
  // combining file trees from more than one snapshot can tell entries
  // apart, and so a consumer can verify this tree matches
  // `execution.snapshotId`.
  snapshotId: string
}

// Ref: Pkl class `evidence.DiffEntry`.
export interface DiffEntry {
  path: string

  changeType: "added" | "removed" | "modified"

  // The two snapshot IDs `restic diff` compared, from its own trailing
  // "statistics" line (`source_snapshot`/`target_snapshot`) -- not
  // re-derived from the top-level `snapshots` listing, which this diff may
  // not even fully overlap with.
  fromSnapshotId: string

  toSnapshotId: string
}

// Ref: Pkl class `evidence.LogExcerpt`.
// A packaged log excerpt -- sourced from the GitHub Actions job-logs API or
// a structured test runner's own captured output (e.g. JUnit
// `<system-out>`), never a raw tee of this workflow's combined stdout.
export interface LogExcerpt {
  source: string

  content: string
}

// Ref: Pkl class `evidence.CapabilityFact`.
// Mirrors diagnostic.Diagnostic (capability-spike/diagnostic/diagnostic.go).
export interface CapabilityFact {
  factId: FactID

  severity: string

  code: string

  vault: string

  message: string
}

// Ref: Pkl class `evidence.CapabilityGrant`.
// Mirrors supervisor.Grant (capability-spike/supervisor/state.go).
export interface CapabilityGrant {
  factId: FactID

  vault: string

  approved: boolean
}

// Ref: Pkl class `evidence.CapabilityObservation`.
// Mirrors runtime.Observation (capability-spike/runtime/proton.go).
export interface CapabilityObservation {
  factId: FactID

  vault: string

  reason: string

  operation: string

  recordedAt: string
}

// Ref: Pkl class `evidence.ReconciliationFlag`.
// Mirrors reconcile.Flag (capability-spike/reconcile/reconcile.go).
export interface ReconciliationFlag {
  kind: FlagKind

  factId: FactID

  detail: string
}

// Ref: Pkl class `evidence.ArtifactHash`.
// One input file's content hash, keyed by path rather than held in a Pkl
// `Mapping` -- the exported JSON transport is a plain array of objects
// (`json.Marshal` has no way to emit a native `Map`), and modeling that
// directly here keeps the generated TypeScript binding (`Array<ArtifactHash>`)
// honest about the shape a consumer actually receives, instead of declaring
// a `Map<string, string>` that `JSON.parse` can never produce.
export interface ArtifactHash {
  path: string

  sha256: string
}

// Ref: Pkl class `evidence.ValidationResult`.
// The exporter's own package-validation verdict -- kept distinct from the
// recorded domain verdict in `ScenarioResult`/`CheckResult` per the issue's
// ask to keep the two identifiable separately.
export interface ValidationResult {
  schemaVersion: string

  artifactHashes: Array<ArtifactHash>

  structurallyValid: boolean

  validationErrors: Array<string>
}

// Ref: Pkl class `evidence.EvidencePackage`.
export interface EvidencePackage {
  schemaVersion: string

  execution: ExecutionIdentity

  scenario: ScenarioResult

  snapshots: Array<SnapshotRef>

  fileTree: Array<FileTreeEntry>

  diff: Array<DiffEntry>

  logs: Array<LogExcerpt>

  // Populated once a capability-spike scenario (CIT-146) is an input;
  // empty listings are valid and expected until then.
  capabilityFacts: Array<CapabilityFact>

  capabilityGrants: Array<CapabilityGrant>

  capabilityObservations: Array<CapabilityObservation>

  reconciliationFlags: Array<ReconciliationFlag>

  validation: ValidationResult
}

// Ref: Pkl type `evidence.Outcome`.
type Outcome = "passed" | "failed" | "skipped" | "eval-error"

// Ref: Pkl type `evidence.FactID`.
type FactID = string

// Ref: Pkl type `evidence.FlagKind`.
type FlagKind = "unapproved-materialization" | "missing-materialization" | "reason-mismatch" | "boundary-bypassed"

// LoadFromPath loads the pkl module at the given path and evaluates it into a Evidence
export const loadFromPath = async (path: string): Promise<Evidence> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<Evidence> =>
  evaluator.evaluateModule(source) as Promise<Evidence>;
