/* This file was generated by `pkl-typescript` from Pkl module `governedVocabulary`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// Modelled on tutorial-app's chapter-1 lesson-2 `PersonalVocabulary.pkl`,
// ownership inverted: the worker may only reference an admitted term,
// never add one. `resolver.Resolve` (../resolver/resolver.go) is the only
// code that reads `admitted`.
export interface GovernedVocabulary {
  requiresVocabularyAdmission: boolean

  admitted: Array<AdmittedTerm>
}

// Ref: Pkl class `governedVocabulary.AdmittedTerm`.
// One admitted mapping from a prose fragment to a stable fact ID.
export interface AdmittedTerm {
  phrase: string

  factId: string

  scope: string

  lossAxes: Array<string>
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a GovernedVocabulary
export const loadFromPath = async (path: string): Promise<GovernedVocabulary> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<GovernedVocabulary> =>
  evaluator.evaluateModule(source) as Promise<GovernedVocabulary>;
