services:
  - type: cron
    name: devpod-keepalive
    runtime: image
    image:
      url: ghcr.io/null-hype/devenv-keepalive@sha256:7bba9fdf8b4909ab2f0442f6afc5ccda0d376c798399b628cb7ee0ec281c1202
      creds:
        fromRegistryCreds:
          name: Citizen6.Librarian6.Refrain4
    schedule: "15 * * * *"
    envVars:
      - key: PROTON_PASS_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: WORKSPACE_ID
        value: devenv-base-gce
