services:
  - type: cron
    name: devpod-keepalive
    runtime: image
    image:
      url: ghcr.io/null-hype/devenv-keepalive:sha-e7cfc7e4655a8d037dbc7f35b11511afcd565ee2
      creds:
        fromRegistryCreds:
          name: ghcr-null-hype
    schedule: "15 * * * *"
    envVars:
      - key: PROTON_PASS_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: WORKSPACE_ID
        value: devenv-base-gce
