services:
  - type: cron
    name: devpod-keepalive
    runtime: image
    image:
      url: ghcr.io/null-hype/devenv-keepalive@sha256:5bf6ec7860295988e202d4ed9c4a917cf1dff609d396e287445eeb35df40d562
      creds:
        fromRegistryCreds:
          name: Citizen6.Librarian6.Refrain4
    schedule: "15 * * * *"
    envVars:
      - key: PROTON_PASS_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: WORKSPACE_ID
        value: devenv-base-gce
