/* Generated directly from this repo's own
 * src/content/tutorial/part-2/chapter-1/lesson-1/_files/pkl/AcpDiagnosticMeta.pkl
 * via `npx @pkl-community/pkl-typescript -o <out> pkl/AcpDiagnosticMeta.pkl`
 * run from that lesson's `_files/` directory. Unlike reconcile.pkl.ts /
 * governedVocabulary.pkl.ts / grant_state.pkl.ts (vendored from an external
 * capability-spike repo because their source .pkl module lives there), this
 * module's source lives in this repo already -- there is nothing to vendor
 * from, so re-running the same command against the same .pkl file and
 * replacing this file wholesale is the entire update path on schema changes. */
/* This file was generated by `pkl-typescript` from Pkl module `acpDiagnosticMeta`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// CIT-245: the schema for the `_meta.diagnostic` extension this lesson's
// recorded ACP exchange carries on its agent response envelope. ACP's own
// JSON-RPC envelope reserves `_meta` on results/notifications for exactly
// this kind of implementation-defined extension -- the envelope itself
// (`jsonrpc`/`id`/`method`/`params`/`result`) is not modelled here, only the
// payload a recording puts inside its `_meta`. `src/lib/acpTraceProtocol.ts`
// is the only code that reads a parsed `_meta.diagnostic`; it treats this
// shape as the contract, not something it derives on its own.
export interface AcpDiagnosticMeta {
  diagnostic: AcpDiagnostic
}

// Ref: Pkl class `acpDiagnosticMeta.AcpDiagnostic`.
export interface AcpDiagnostic {
  severity: "info" | "warning" | "error"

  code: string

  message: string

  // Free-form provenance for where this diagnostic came from -- a scenario
  // name or subsystem, not a file path (evidence provenance lives on the
  // frame that carries this diagnostic, see `AcpFrame.provenance` in
  // acpTraceProtocol.ts).
  source: string
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a AcpDiagnosticMeta
export const loadFromPath = async (path: string): Promise<AcpDiagnosticMeta> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<AcpDiagnosticMeta> =>
  evaluator.evaluateModule(source) as Promise<AcpDiagnosticMeta>;
